"""Add military

Revision ID: 11541d9c6f4a
Revises: ada7f36a9f02
Create Date: 2022-03-18 05:29:47.068252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11541d9c6f4a'
down_revision = 'ada7f36a9f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_unit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_unit_type_id'), 'staff_unit_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_unit_type_id'), table_name='staff_unit_type')
    op.drop_table('staff_unit_type')
    # ### end Alembic commands ###
