"""Add sap

Revision ID: 11a64ab00db2
Revises: 24d6c0ae4271
Create Date: 2022-03-17 14:01:16.636911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a64ab00db2'
down_revision = '24d6c0ae4271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
