"""Add sap

Revision ID: 17f290b32277
Revises: 11a64ab00db2
Create Date: 2022-03-17 14:02:45.850039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f290b32277'
down_revision = '11a64ab00db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
