"""Add military

Revision ID: 2f7994bc48ae
Revises: 7017b178878d
Create Date: 2022-03-18 05:07:15.987567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7994bc48ae'
down_revision = '7017b178878d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_service_attitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_military_service_attitude_id'), 'military_service_attitude', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_military_service_attitude_id'), table_name='military_service_attitude')
    op.drop_table('military_service_attitude')
    # ### end Alembic commands ###
