"""Add grade

Revision ID: 366a9fd8f1f0
Revises: ec3ff6cd49dc
Create Date: 2022-03-17 12:34:52.644484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366a9fd8f1f0'
down_revision = 'ec3ff6cd49dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_id'), 'grade', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_id'), table_name='grade')
    op.drop_table('grade')
    # ### end Alembic commands ###
