"""Add sap

Revision ID: 6b2e1cda837a
Revises: af47e388feb3
Create Date: 2022-03-17 13:26:19.764748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2e1cda837a'
down_revision = 'af47e388feb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('nationalitySAPId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationalitySAPId'], ['nationality_sap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_id'), 'nationality', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nationality_id'), table_name='nationality')
    op.drop_table('nationality')
    # ### end Alembic commands ###
