"""Add position

Revision ID: 7500e7a63137
Revises: 5bb4d066c736
Create Date: 2022-03-18 11:14:14.608557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7500e7a63137'
down_revision = '5bb4d066c736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
