"""Add military

Revision ID: 91f95d69e802
Revises: c42b39b6af95
Create Date: 2022-03-18 06:09:16.245616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f95d69e802'
down_revision = 'c42b39b6af95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_unit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_type_id'), 'organization_unit_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_unit_type_id'), table_name='organization_unit_type')
    op.drop_table('organization_unit_type')
    # ### end Alembic commands ###
