"""Add military

Revision ID: a245aacf939c
Revises: 91f95d69e802
Create Date: 2022-03-18 06:23:28.315923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a245aacf939c'
down_revision = '91f95d69e802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_type_id'), 'order_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_type_id'), table_name='order_type')
    op.drop_table('order_type')
    # ### end Alembic commands ###
