"""Add military

Revision ID: ada7f36a9f02
Revises: 2f7994bc48ae
Create Date: 2022-03-18 05:18:41.213147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada7f36a9f02'
down_revision = '2f7994bc48ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marital_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.Column('genderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genderId'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marital_status_id'), 'marital_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marital_status_id'), table_name='marital_status')
    op.drop_table('marital_status')
    # ### end Alembic commands ###
