"""Add sap

Revision ID: af47e388feb3
Revises: 366a9fd8f1f0
Create Date: 2022-03-17 12:47:19.025238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af47e388feb3'
down_revision = '366a9fd8f1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality_sap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nationality_sap_id'), 'nationality_sap', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nationality_sap_id'), table_name='nationality_sap')
    op.drop_table('nationality_sap')
    # ### end Alembic commands ###
