"""Add saewq

Revision ID: cbd829e2e737
Revises: cd21740c541f
Create Date: 2022-03-17 14:06:14.179047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd829e2e737'
down_revision = 'cd21740c541f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
