"""Add saewq

Revision ID: cd21740c541f
Revises: edf5983e37ca
Create Date: 2022-03-17 14:05:18.194065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd21740c541f'
down_revision = 'edf5983e37ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
