"""Add position

Revision ID: e8bbdbdef898
Revises: 7500e7a63137
Create Date: 2022-03-18 11:15:43.882497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bbdbdef898'
down_revision = '7500e7a63137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
