"""Add sap

Revision ID: edf5983e37ca
Revises: 263033e2a50b
Create Date: 2022-03-17 14:04:20.757379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf5983e37ca'
down_revision = '263033e2a50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
